# Generated by Django 4.1 on 2022-08-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Nombre de la pelicula', max_length=35)),
                ('descripcion', models.TextField(help_text='Descripcion de la pelicula', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del director', max_length=64)),
                ('peliculas', models.ManyToManyField(to='Cine.pelicula')),
            ],
        ),
    ]
