# Generated by Django 4.1 on 2022-08-26 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cine', '0002_alter_pelicula_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='nombre',
            new_name='name',
        ),
    ]
